### ISSUE TITLE
Error when invalid URL

### ISSUE THREAD

**Issue by SamuelTissot** [SamuelTissot/mPing.go#1]
```
Get www.lightspeedhq.com/: unsupported protocol scheme ""
0.00s elapsed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x11ebb1d]

goroutine 5 [running]:
main.fetch(0x7fff5fbff798, 0x15, 0xc4200181e0)
        /Users/samuel.tissot/go_code/workspace/src/github.com/SamuelTissot/mping/main.go:31 +0x11d
created by main.main
        /Users/samuel.tissot/go_code/workspace/src/github.com/SamuelTissot/mping/main.go:16 +0xe8
```

**Comment by SamuelTissot** [comment]
no activity
